// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	CreateBook(ctx context.Context, in *BookMessage, opts ...grpc.CallOption) (*BookMessage, error)
	MultiCreateBook(ctx context.Context, in *ListBooksMessage, opts ...grpc.CallOption) (*ListBooksMessage, error)
	DescribeBook(ctx context.Context, in *CurrentBookMessage, opts ...grpc.CallOption) (*BookMessage, error)
	ListBooks(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBooksMessage, error)
	UpdateBook(ctx context.Context, in *BookMessage, opts ...grpc.CallOption) (*BookMessage, error)
	RemoveBook(ctx context.Context, in *CurrentBookMessage, opts ...grpc.CallOption) (*BookMessage, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *BookMessage, opts ...grpc.CallOption) (*BookMessage, error) {
	out := new(BookMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) MultiCreateBook(ctx context.Context, in *ListBooksMessage, opts ...grpc.CallOption) (*ListBooksMessage, error) {
	out := new(ListBooksMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/MultiCreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DescribeBook(ctx context.Context, in *CurrentBookMessage, opts ...grpc.CallOption) (*BookMessage, error) {
	out := new(BookMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/DescribeBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) ListBooks(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBooksMessage, error) {
	out := new(ListBooksMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *BookMessage, opts ...grpc.CallOption) (*BookMessage, error) {
	out := new(BookMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) RemoveBook(ctx context.Context, in *CurrentBookMessage, opts ...grpc.CallOption) (*BookMessage, error) {
	out := new(BookMessage)
	err := c.cc.Invoke(ctx, "/ozonva.book.api.BookService/RemoveBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	CreateBook(context.Context, *BookMessage) (*BookMessage, error)
	MultiCreateBook(context.Context, *ListBooksMessage) (*ListBooksMessage, error)
	DescribeBook(context.Context, *CurrentBookMessage) (*BookMessage, error)
	ListBooks(context.Context, *empty.Empty) (*ListBooksMessage, error)
	UpdateBook(context.Context, *BookMessage) (*BookMessage, error)
	RemoveBook(context.Context, *CurrentBookMessage) (*BookMessage, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) CreateBook(context.Context, *BookMessage) (*BookMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedBookServiceServer) MultiCreateBook(context.Context, *ListBooksMessage) (*ListBooksMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiCreateBook not implemented")
}
func (UnimplementedBookServiceServer) DescribeBook(context.Context, *CurrentBookMessage) (*BookMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeBook not implemented")
}
func (UnimplementedBookServiceServer) ListBooks(context.Context, *empty.Empty) (*ListBooksMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (UnimplementedBookServiceServer) UpdateBook(context.Context, *BookMessage) (*BookMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedBookServiceServer) RemoveBook(context.Context, *CurrentBookMessage) (*BookMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBook not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*BookMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_MultiCreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).MultiCreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/MultiCreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).MultiCreateBook(ctx, req.(*ListBooksMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DescribeBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentBookMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DescribeBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/DescribeBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DescribeBook(ctx, req.(*CurrentBookMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ListBooks(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*BookMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_RemoveBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentBookMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).RemoveBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonva.book.api.BookService/RemoveBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).RemoveBook(ctx, req.(*CurrentBookMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonva.book.api.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "MultiCreateBook",
			Handler:    _BookService_MultiCreateBook_Handler,
		},
		{
			MethodName: "DescribeBook",
			Handler:    _BookService_DescribeBook_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _BookService_ListBooks_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "RemoveBook",
			Handler:    _BookService_RemoveBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
